FROM golang:1.22 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags "-s -w -X pubsub-chat/pkg/version.Tag=prod" \
    -o /bin/pubsub ./cmd/server


FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=builder /bin/pubsub /pubsub
COPY web /web
ENV HTTP_ADDR=:8080
EXPOSE 8080
USER 65532:65532
ENTRYPOINT ["/pubsub"]